.MODEL SMALL
.STACK 100H
.DATA
 
MSG1 DB "HELLO WORLD",0DH,0AH,24H

.CODE

MAIN PROC
    
    MOV AX,@DATA
    MOV DS,AX
    

    ; FOR CREATING A COUNTER FOR "WHILE LOOP"
    MOV CX,5H
    
    
    ;(20-32) WHILE LOOP
    START:
    
    ;() CHECKING IF THE LOOP RUNED 5 TIMES OR NOT
    CMP CX,0H
    JE EXIT ; THIS JE(JUMP EQUAL) MEANS IF CX AND 0H IS EQUAL THEN IT WILL GO TO LEVEL EXIT.SEE DEFINATION OF LEVEL IN THE ADDITIONAL INFO 
    
    ;FOR MESSAGE(27-30)
    LEA DX,MSG1
    MOV AH,09H
    INT 21H 
 
    DEC CX ;DECREASING THE VALUE OF CX BY 1
    JMP START
     
    

    EXIT:
    MOV AH,4CH
    INT 21H
    
    MAIN ENDP
END MAIN 

;ADDITIONAL INFO

;LEVEL:
;LEVEL IS GIVING A NAME TO BULTIPLE LINE OF CODE
;THIS IS HOW IT IS DECLARED: 
;
; NAMEOFLEVEL:
;

;BASIC STRUCTURE OF A WHILE LOOP:
; MOV CX,05H  --> HOW MANY TIMES YOU WANT TO RUN THE LOOP
;START:
;CMP CX,0H --> COMPARING IF CX IS EQUAL 0 OR NOT
; 
; HERE THE TASK THAT YOU WANT TO DO FIVE TIME  
;
;DEC CX --> DECREAISNG THE VALOUE OF CX BY 1
;
;JMP START