.MODEL SMALL
.STACK 100H                         

.DATA

NEWLINE DB "",0AH,0DH,24H 

MSG1 DB "NUMBER ",0AH,0DH,24H
MSG2 DB "NOT NUMBER ",0AH,0DH,24H
  

.CODE

MAIN PROC   
    
    MOV AX,@DATA
    MOV DS,AX
    
    
    ;(22-24)TAKING USER INPUT
    
    MOV AH,01H
    INT 21H
    MOV BL,AL 
    
    ;(28-30) --> PRINTING NEW LINE
 
    LEA DX,NEWLINE
    MOV AH,09H
    INT 21H
    
    ;(34-38) --> CHECKING NUMBER OR NOT(1ST CHECKING IF THE USER INPUT'S ASCII VALUE IS LESS THAN 30H ASSCI VALUE OR NOT THEN CHECKING MORE THAN 39H ASSCI VALUE OR OR NOT  AND DEPENDING ON THAT SENDING ITT TO INVALIED LEVEL)
    
    CMP BL,30H
    JL INVALID
    
    CMP BL,39H
    JG INVALID
    
    
    ;(21-44) --> PRINTING MESSAGE 1
    LEA DX,MSG1
    MOV AH,09H
    INT 21H 
    
    ;(47) --> TESK COMPLETED SO SENDING IT TO EXIT 
    JMP EXIT
    

    ;(53-55) --> PRINTING MESSAGE 1
    INVALID: 
    
    LEA DX,MSG2
    MOV AH,09H
    INT 21H 
    
    
    EXIT: 
    MOV AH,4CH
    INT 21H
    
    MAIN ENDP
END MAIN  
