.MODEL SMALL
.STACK 100H                         

.DATA

NEWLINE DB "",0AH,0DH,24H 

MSG1 DB "EVEN NUMBER ",0AH,0DH,24H 
MSG2 DB "ODD NUMBER ",0AH,0DH,24H
MSG3 DB "NOT A NUMBER ",0AH,0DH,24H  

.CODE

MAIN PROC   
    
    MOV AX,@DATA
    MOV DS,AX
    
    
    ;(22-24)TAKING USER INPUT
    
    MOV AH,01H
    INT 21H
    MOV BL,AL  ; MOVE THE VALUE TO BL REGISTER AS IT CRAETE PROBLEM IF WE DO THE CALCULATION IN THE AL REGISTER WHILE PRINTING NEW LINE
    
    ;(28-30) --> PRINTING MSG FROM .DATA. NEWLINE --> ITS JOB IS TO PRINT A NEWLINE 
 
    LEA DX,NEWLINE
    MOV AH,09H
    INT 21H
    
    ;(34-37) --> CHECKING NUMBER OR NOT(1ST CHECKING LESS THAN 30H ASSCI VALUE OR NOT THEN CHECKING MORE THAN 39H ASSCI VALUE OR OR NOT  AND DEPENDING ON THAT SENDING IT TO INVALIED LEVEL)
    
    CMP BL,30H
    JL INVALID
    CMP BL,39H
    JG INVALID
    
    ;(40-41) --> CHECKING EVEN OR NOT:TEST IS DOING & OPERATION AND SAVING THE RESULT ON CARRY FLAG, JZ IS COMPARING IF CARRY ZERO OR NOT (MEAANS CF FLAG IS TRUE OR NOT) , IF TRUE THEN SENDING THE CONTROL TO EVEN LEVEL ELSE GOING TO ODD LEVEL
    TEST BL,1B
    JZ EVEN
    
    ;(45-47) --> PRINTING MSG2    
    ODD:
    LEA DX,MSG2
    MOV AH,09H
    INT 21H
    
    ;(50) --> TESK COMPLETED SO SENDING IT TO EXIT 
    JMP EXIT   
    
    ;(54-56) --> PRINTING MSG1    
    EVEN: 
    LEA DX,MSG1
    MOV AH,09H
    INT 21H
     
    ;(59) --> SIMILARLY,TESK COMPLETED SO SENDING IT TO EXIT
    JMP EXIT 
    
    INVALID: 
    ;(63-65) --> PRINTING MSG3 
    LEA DX,MSG3
    MOV AH,09H
    INT 21H 
    
    
    EXIT: 
    MOV AH,4CH
    INT 21H
    
    MAIN ENDP
END MAIN  
