.MODEL SMALL
.STACK 100H                         

.DATA 
.CODE

MAIN PROC
    MOV AX,@DATA
    MOV DS,AX 
    
    ;() CHOOSING VALUE AND STORING IT ON AL
    MOV AL,11110000B
    
    ;() CLEARING BX FOR FUTURE USE
    MOV BX,0H 
    
    ;() CREATING A COUNTER REGISTOR FOR RUNNING LOOP FOR 8 TIMES
    MOV CX,08H
    
    ;RUNNING A FOR LOOP FOR 8 TIME
    START:
    SHR AL,1 ;DOING 1 RIGHT SHIFT ON AL .IT WILL RUN 8 TIMES
    RCL BL,1 ;DOING 1 ROTATE CARRY LEFT ON AL .IT WILL RUN 8 TIMES
    
    
    LOOP START
    
    ;()EXIT THE CODE
    EXIT: 
    MOV AH,4CH
    INT 21H
    
    MAIN ENDP
END MAIN  

;HERE,
;AL=11110000=240=F0
;EXPECTED RESULT
;BL=00001111=15=0F